name: build sakura

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/*
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'

  pull_request:
    branches:
      - master
      - feature/*
      - release/*
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    name: MSBuild
    runs-on: windows-latest

    strategy:
      matrix:
        config:
          - Debug
          - Release
        platform:
          - Win32
          - x64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    ## see https://github.com/actions/checkout
    - uses: actions/checkout@v2

    ## see https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild
      run: build-sln.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    - name: Install Locale Emulator
      run: choco install locale-emulator -y
      shell: cmd

    - name: Build HTML Help
      run: build-chm.bat
      shell: cmd

    - name: Build installer with Inno Setup
      run: build-installer.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    - name: zipArtifacts
      run: zipArtifacts.bat ${{ matrix.platform }} ${{ matrix.config }}
      if: ${{ matrix.config == 'Release' }}
      shell: cmd

    ## see https://github.com/actions/upload-artifact
    - name: Upload Installer
      uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: Installer ${{ matrix.platform }} ${{ matrix.config }}
        path: 'sakura-*-Installer.zip'

    - name: Upload Installer MD5
      uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: Installer MD5 ${{ matrix.platform }} ${{ matrix.config }}
        path: 'sakura-*-Installer.zip.md5'

    - name: Upload Exe
      uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: Exe ${{ matrix.platform }} ${{ matrix.config }}
        path: 'sakura-*-Exe.zip'

    - name: Upload Exe MD5
      uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: Exe MD5 ${{ matrix.platform }} ${{ matrix.config }}
        path: 'sakura-*-Exe.zip.md5'

    - name: Upload Log
      uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: Log ${{ matrix.platform }} ${{ matrix.config }}
        path: 'sakura-*-Log.zip'

    - name: Upload Asm
      uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: Asm ${{ matrix.platform }} ${{ matrix.config }}
        path: 'sakura-*-Asm.zip'

    - name: Upload Dev
      uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: Dev ${{ matrix.platform }} ${{ matrix.config }}
        path: 'sakura-*-Dev.zip'

  sonar:
    name: SonarCloud
    runs-on: windows-latest

    env:
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: Release
      SONAR_QUBE_VERSION: '4.5.0.2216'

    if: github.event_name != 'pull_request'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup environment variables
      run: |
        echo "SONAR_USER_HOME=${{ runner.temp }}\sonar-user-home" >> $env:GITHUB_ENV
        echo "OUT_DIR=${{ github.workspace }}\$env:BUILD_PLATFORM\$env:BUILD_CONFIGURATION" >> $env:GITHUB_ENV

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install Build-Wrapper
      working-directory: ${{ runner.temp }}
      run: |
        Invoke-WebRequest -OutFile build-wrapper-win-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
        7z x build-wrapper-win-x86.zip

    - name: Build with Build-Wrapper
      run: |
        ${{ runner.temp }}\build-wrapper-win-x86\build-wrapper-win-x86-64.exe --out-dir bw-output MsBuild.exe /p:Platform=$env:BUILD_PLATFORM,Configuration=$env:BUILD_CONFIGURATION /t:ReBuild
        echo "${{ env.OUT_DIR }}" >> $env:GITHUB_PATH

    - name: Install OpenCppCoverage with XmlExporter
      working-directory: ${{ runner.temp }}
      run: |
        choco install OpenCppCoverage -y
        Invoke-WebRequest -OutFile XmlExporter-x64.zip https://github.com/berryzplus/XmlExporter/releases/download/v1.0.0/XmlExporter-x64.zip
        7z e XmlExporter-x64.zip
        Move-Item -Path XmlExporter.dll -Destination "C:\Program Files\OpenCppCoverage\Plugins\Exporter\xml.dll"
        echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

    - name: Run Tests
      shell: cmd
      run: OpenCppCoverage.exe
        --export_type xml:tests1-coverage.xml
        --modules ${{ github.workspace }}\${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\tests1.exe
        --sources ${{ github.workspace }}
        --working_dir ${{ github.workspace }}\${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}
        --cover_children
        --
        ${{ github.workspace }}\tests\build\${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\unittests\tests1.exe
        --gtest_output=xml:tests1-googletest.xml

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache SonarResults
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.SONAR_USER_HOME }}\.sonar\cache
          ${{ runner.temp }}\sonar-scanner-cache
        key: sonar-scanner-cache-${{ env.SONAR_QUBE_VERSION }}-${{ github.sha }}
        restore-keys: sonar-scanner-cache-${{ env.SONAR_QUBE_VERSION }}-

    - name: Install SonarScanner
      working-directory: ${{ runner.temp }}
      run: |
        Invoke-WebRequest -OutFile sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_QUBE_VERSION }}.zip
        7z rn sonar-scanner.zip sonar-scanner-${{ env.SONAR_QUBE_VERSION }} sonar-scanner
        7z x sonar-scanner.zip
        $ShimGen = "$env:ChocolateyInstall\tools\shimgen.exe"
        $SonarScanner = "$env:ChocolateyInstall\bin\sonar-scanner.exe"
        $SonarScannerBat = "${{ runner.temp }}\sonar-scanner\bin\sonar-scanner.bat"
        Start-Process -FilePath $ShimGen -ArgumentList "-o `"$SonarScanner`" -p `"$SonarScannerBat`"" -Wait

    - name: Analyze with SonarScanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN
      run: sonar-scanner.exe
        -D"sonar.organization=${{ github.repository_owner }}"
        -D"sonar.projectKey=$('${{ github.repository }}' -replace '/', '_')"
        -D"sonar.host.url=https://sonarcloud.io"
        -D"sonar.sourceEncoding=UTF-8"
        -D"sonar.sources=."
        -D"sonar.cfamily.build-wrapper-output=bw-output"
        -D"sonar.cfamily.cache.enabled=true"
        -D"sonar.cfamily.cache.path=${{ runner.temp }}\sonar-scanner-cache"
        -D"sonar.cfamily.cppunit.reportPath=tests1-googletest.xml"
        -D"sonar.cfamily.threads=2"
        -D"sonar.coverageReportPaths=tests1-coverage.xml"
        -D"sonar.exclusions=HeaderMake,tests\googletest\**\*,tests\build\**\*"
